# Generated by Django 3.2.4 on 2021-11-30 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuario', models.CharField(error_messages={'max_length': 'Tu nombre debe teer 80 caracteres máximo', 'required': 'Necesitas un nombre de usuario', 'unique': 'Este Usuario ya esta en uso'}, max_length=80, unique=True)),
                ('nombre_1', models.CharField(error_messages={'max_length': 'Tu nombre debe teer 80 caracteres máximo', 'required': 'Necesitas escribir un nombre'}, max_length=80)),
                ('nombre_2', models.CharField(blank=True, error_messages={'max_length': 'Tu nombre debe teer 80 caracteres máximo'}, max_length=80)),
                ('apellido_p', models.CharField(error_messages={'max_length': 'Tu apellido debe teer 110 caracteres máximo', 'required': 'Necesitas escribir un apellido'}, max_length=110)),
                ('apellido_m', models.CharField(blank=True, error_messages={'max_length': 'Tu apellido debe teer 110 caracteres máximo'}, max_length=110)),
                ('correo', models.EmailField(error_messages={'invalid': 'Necesitas escribir un email valido', 'max_length': 'Tu email solo puede tener 150 caracteres máximo', 'required': 'Es necesario dar un email', 'unique': 'Este email ya esta en uso'}, max_length=150, unique=True)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Administrador'), (2, 'Usuario')])),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
