# Generated by Django 3.2.4 on 2021-11-30 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='dependencia_origen',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='oficios.dependencia'),
        ),
    ]
