# Generated by Django 3.2.4 on 2022-02-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuarios_dependencia_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrador'), (2, 'Usuario_Nivel_1'), (3, 'Usuario_Nivel_2'), (4, 'Usuario_Nivel_3'), (5, 'Usuario_Nivel_4')]),
        ),
    ]
