# Generated by Django 3.2.4 on 2022-03-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0002_auto_20220213_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='mes',
            field=models.CharField(choices=[('Ene', 'Enero'), ('Feb', 'Febrero'), ('Mar', 'Marzo'), ('Abr', 'Abril'), ('May', 'Mayo'), ('Jun', 'Junio'), ('Jul', 'Julio'), ('Ago', 'Agosto'), ('Sep', 'Septiembre'), ('Oct', 'Octubre'), ('Nov', 'Noviembre'), ('Dic', 'Diciembre')], default='Mar', max_length=3),
        ),
    ]
