# Generated by Django 3.2.4 on 2021-11-30 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id_dependencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('siglas', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('folio', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mes', models.CharField(choices=[('Ene', 'Enero'), ('Feb', 'Febrero'), ('Mar', 'Marzo'), ('Abr', 'Abril'), ('May', 'Mayo'), ('Jun', 'Junio'), ('Jul', 'Julio'), ('Ago', 'Agosto'), ('Sep', 'Septiembre'), ('Oct', 'Octubre'), ('Nov', 'Noviembre'), ('Dic', 'Diciembre')], default='Nov', max_length=3)),
                ('año', models.IntegerField(default=2021, error_messages={'required': 'Este campo es obligatorio'})),
                ('asunto', models.TextField()),
                ('estatus', models.CharField(choices=[('NU', 'Nuevo'), ('NR', 'No Revisado'), ('L', 'Leido'), ('S', 'Seguimiento'), ('C', 'Completado')], default='NU', max_length=2)),
                ('documento', models.FileField(upload_to='static/pdf')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencia_origen', to='oficios.dependencia')),
                ('turnado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencia_destino', to='oficios.dependencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OficioRespuesta',
            fields=[
                ('id_oficio_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('asunto', models.TextField()),
                ('documento', models.FileField(upload_to='static/pdf')),
                ('id_oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folio_oficio', to='oficios.oficio')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
